name: Super-Linter

on: push

jobs:

  super-lint:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        run: |-
          ./gradlew assembble
      
      - name: Test
        run: |-
          ./gradlew check
          
      - name: Build image
        run: |-
          ./gradlew Image_docker

      - name: Push Image
        run: |-
          ./docker push .../tp_devops
