name: Super-Linter

on: push

jobs:

  super-lint:
    name: Build the app
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        run: |-
          ./gradlew assemble
      
      - name: Test
        run: |-
          ./gradlew check
          
      - name: Build image
        run: |-
          ./gradlew Image_docker

      - name: Push Image
        run: |-
          ./docker push .../tp_devops
